# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'dlouhodobka_testpJWgtx.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.setWindowModality(Qt.NonModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(1024, 768)
        icon = QIcon()
        icon.addFile(u"../../PycharmProjects/Nov\u00fdProjekt/GraduationThesis/window-icon.png", QSize(), QIcon.Normal, QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.QTab1 = QTabWidget(self.centralwidget)
        self.QTab1.setObjectName(u"QTab1")
        self.QTab1.setGeometry(QRect(-2, 0, 1032, 772))
        palette = QPalette()
        brush = QBrush(QColor(211, 211, 211, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush)
        brush1 = QBrush(QColor(0, 170, 255, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Light, brush1)
        palette.setBrush(QPalette.Active, QPalette.Base, brush)
        palette.setBrush(QPalette.Active, QPalette.Window, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Light, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush)
        palette.setBrush(QPalette.Disabled, QPalette.Light, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush)
        self.QTab1.setPalette(palette)
        self.QTab1.setStyleSheet(u"background-color: rgb(211, 211, 211);")
        self.tab_1 = QWidget()
        self.tab_1.setObjectName(u"tab_1")
        self.line = QFrame(self.tab_1)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(0, 380, 475, 8))
        self.line.setContextMenuPolicy(Qt.NoContextMenu)
        self.line.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.line.setFrameShadow(QFrame.Plain)
        self.line.setLineWidth(1)
        self.line.setFrameShape(QFrame.HLine)
        self.CPU_MAIN_LABEL = QLabel(self.tab_1)
        self.CPU_MAIN_LABEL.setObjectName(u"CPU_MAIN_LABEL")
        self.CPU_MAIN_LABEL.setGeometry(QRect(35, 15, 165, 45))
        self.CPU_MAIN_LABEL.setFrameShadow(QFrame.Plain)
        self.CPU_MAIN_LABEL.setTextFormat(Qt.AutoText)
        self.GPU_MAIN_LABEL = QLabel(self.tab_1)
        self.GPU_MAIN_LABEL.setObjectName(u"GPU_MAIN_LABEL")
        self.GPU_MAIN_LABEL.setGeometry(QRect(35, 395, 191, 45))
        self.GPU_MAIN_LABEL.setContextMenuPolicy(Qt.ActionsContextMenu)
        self.GPU_MAIN_LABEL.setFrameShape(QFrame.NoFrame)
        self.cpu_frequency_label = QLabel(self.tab_1)
        self.cpu_frequency_label.setObjectName(u"cpu_frequency_label")
        self.cpu_frequency_label.setGeometry(QRect(55, 150, 231, 21))
        self.cpu_frequency_label.setStyleSheet(u"color: rgb(40, 125, 200);")
        self.cpu_frequency_label.setFrameShadow(QFrame.Sunken)
        self.cpu_frequency_label.setLineWidth(-1)
        self.cpu_frequency_label.setTextFormat(Qt.AutoText)
        self.cpu_cores_label = QLabel(self.tab_1)
        self.cpu_cores_label.setObjectName(u"cpu_cores_label")
        self.cpu_cores_label.setGeometry(QRect(55, 110, 161, 21))
        self.cpu_cores_label.setStyleSheet(u"color: rgb(40, 125, 200);")
        self.cpu_cores_label.setFrameShadow(QFrame.Sunken)
        self.cpu_cores_label.setLineWidth(-1)
        self.cpu_cores_label.setTextFormat(Qt.AutoText)
        self.cpu_cores_label.setAlignment(Qt.AlignBottom|Qt.AlignLeading|Qt.AlignLeft)
        self.cpu_cores_label.setMargin(0)
        self.cpu_name_label = QLabel(self.tab_1)
        self.cpu_name_label.setObjectName(u"cpu_name_label")
        self.cpu_name_label.setGeometry(QRect(55, 70, 411, 21))
        self.cpu_name_label.setStyleSheet(u"color: rgb(40, 125, 200);")
        self.cpu_name_label.setFrameShadow(QFrame.Sunken)
        self.cpu_name_label.setLineWidth(-1)
        self.cpu_name_label.setTextFormat(Qt.AutoText)
        self.cpu_name_label.setAlignment(Qt.AlignBottom|Qt.AlignLeading|Qt.AlignLeft)
        self.cpu_name_label.setMargin(0)
        self.cpu_min_temperature_label = QLabel(self.tab_1)
        self.cpu_min_temperature_label.setObjectName(u"cpu_min_temperature_label")
        self.cpu_min_temperature_label.setGeometry(QRect(55, 230, 231, 21))
        self.cpu_min_temperature_label.setStyleSheet(u"color: rgb(40, 125, 200);")
        self.cpu_min_temperature_label.setFrameShadow(QFrame.Sunken)
        self.cpu_min_temperature_label.setLineWidth(-1)
        self.cpu_min_temperature_label.setTextFormat(Qt.AutoText)
        self.cpu_max_temperature_label = QLabel(self.tab_1)
        self.cpu_max_temperature_label.setObjectName(u"cpu_max_temperature_label")
        self.cpu_max_temperature_label.setGeometry(QRect(55, 270, 231, 21))
        self.cpu_max_temperature_label.setContextMenuPolicy(Qt.DefaultContextMenu)
        self.cpu_max_temperature_label.setStyleSheet(u"color: rgb(40, 125, 200);")
        self.cpu_max_temperature_label.setFrameShadow(QFrame.Sunken)
        self.cpu_max_temperature_label.setLineWidth(-1)
        self.cpu_max_temperature_label.setTextFormat(Qt.AutoText)
        self.cpu_load_label = QLabel(self.tab_1)
        self.cpu_load_label.setObjectName(u"cpu_load_label")
        self.cpu_load_label.setGeometry(QRect(55, 310, 231, 21))
        self.cpu_load_label.setStyleSheet(u"color: rgb(40, 125, 200);")
        self.cpu_load_label.setFrameShadow(QFrame.Sunken)
        self.cpu_load_label.setLineWidth(-1)
        self.cpu_load_label.setTextFormat(Qt.AutoText)
        self.gpu_name_label = QLabel(self.tab_1)
        self.gpu_name_label.setObjectName(u"gpu_name_label")
        self.gpu_name_label.setGeometry(QRect(55, 455, 231, 21))
        self.gpu_name_label.setStyleSheet(u"color: rgb(40, 125, 200);")
        self.gpu_name_label.setFrameShadow(QFrame.Sunken)
        self.gpu_name_label.setLineWidth(-1)
        self.gpu_name_label.setTextFormat(Qt.AutoText)
        self.gpu_total_memory_label = QLabel(self.tab_1)
        self.gpu_total_memory_label.setObjectName(u"gpu_total_memory_label")
        self.gpu_total_memory_label.setGeometry(QRect(55, 495, 231, 21))
        self.gpu_total_memory_label.setStyleSheet(u"color: rgb(40, 125, 200);")
        self.gpu_total_memory_label.setFrameShadow(QFrame.Sunken)
        self.gpu_total_memory_label.setLineWidth(-1)
        self.gpu_total_memory_label.setTextFormat(Qt.AutoText)
        self.gpu_memory_used_label = QLabel(self.tab_1)
        self.gpu_memory_used_label.setObjectName(u"gpu_memory_used_label")
        self.gpu_memory_used_label.setGeometry(QRect(55, 655, 301, 21))
        self.gpu_memory_used_label.setStyleSheet(u"color: rgb(40, 125, 200);")
        self.gpu_memory_used_label.setFrameShadow(QFrame.Sunken)
        self.gpu_memory_used_label.setLineWidth(-1)
        self.gpu_memory_used_label.setTextFormat(Qt.AutoText)
        self.gpu_fan_load_label = QLabel(self.tab_1)
        self.gpu_fan_load_label.setObjectName(u"gpu_fan_load_label")
        self.gpu_fan_load_label.setGeometry(QRect(55, 695, 311, 21))
        self.gpu_fan_load_label.setStyleSheet(u"color: rgb(40, 125, 200);")
        self.gpu_fan_load_label.setFrameShadow(QFrame.Sunken)
        self.gpu_fan_load_label.setLineWidth(-1)
        self.gpu_fan_load_label.setTextFormat(Qt.AutoText)
        self.gpu_temperature_label = QLabel(self.tab_1)
        self.gpu_temperature_label.setObjectName(u"gpu_temperature_label")
        self.gpu_temperature_label.setGeometry(QRect(55, 535, 231, 21))
        self.gpu_temperature_label.setStyleSheet(u"color: rgb(40, 125, 200);")
        self.gpu_temperature_label.setFrameShadow(QFrame.Sunken)
        self.gpu_temperature_label.setLineWidth(-1)
        self.gpu_temperature_label.setTextFormat(Qt.AutoText)
        self.gpu_min_temperature_label = QLabel(self.tab_1)
        self.gpu_min_temperature_label.setObjectName(u"gpu_min_temperature_label")
        self.gpu_min_temperature_label.setGeometry(QRect(55, 575, 291, 21))
        self.gpu_min_temperature_label.setStyleSheet(u"color: rgb(40, 125, 200);")
        self.gpu_min_temperature_label.setFrameShadow(QFrame.Sunken)
        self.gpu_min_temperature_label.setLineWidth(-1)
        self.gpu_min_temperature_label.setTextFormat(Qt.AutoText)
        self.cpu_actual_temperature_label = QLabel(self.tab_1)
        self.cpu_actual_temperature_label.setObjectName(u"cpu_actual_temperature_label")
        self.cpu_actual_temperature_label.setGeometry(QRect(55, 190, 231, 21))
        self.cpu_actual_temperature_label.setStyleSheet(u"color: rgb(40, 125, 200);")
        self.cpu_actual_temperature_label.setFrameShadow(QFrame.Sunken)
        self.cpu_actual_temperature_label.setLineWidth(-1)
        self.cpu_actual_temperature_label.setTextFormat(Qt.AutoText)
        self.gpu_max_temp_label = QLabel(self.tab_1)
        self.gpu_max_temp_label.setObjectName(u"gpu_max_temp_label")
        self.gpu_max_temp_label.setGeometry(QRect(55, 615, 271, 21))
        self.gpu_max_temp_label.setStyleSheet(u"color: rgb(40, 125, 200);")
        self.gpu_max_temp_label.setFrameShadow(QFrame.Sunken)
        self.gpu_max_temp_label.setLineWidth(-1)
        self.gpu_max_temp_label.setTextFormat(Qt.AutoText)
        self.line_2 = QFrame(self.tab_1)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(55, 300, 420, 3))
        palette1 = QPalette()
        brush2 = QBrush(QColor(175, 175, 175, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Button, brush2)
        brush3 = QBrush(QColor(6, 180, 255, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Light, brush3)
        palette1.setBrush(QPalette.Active, QPalette.Base, brush2)
        palette1.setBrush(QPalette.Active, QPalette.Window, brush2)
        palette1.setBrush(QPalette.Inactive, QPalette.Button, brush2)
        palette1.setBrush(QPalette.Inactive, QPalette.Light, brush3)
        palette1.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        palette1.setBrush(QPalette.Inactive, QPalette.Window, brush2)
        palette1.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette1.setBrush(QPalette.Disabled, QPalette.Light, brush3)
        palette1.setBrush(QPalette.Disabled, QPalette.Base, brush2)
        palette1.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        self.line_2.setPalette(palette1)
        self.line_2.setStyleSheet(u"background-color: rgb(175, 175, 175);")
        self.line_2.setFrameShape(QFrame.HLine)
        self.line_2.setFrameShadow(QFrame.Sunken)
        self.line_3 = QFrame(self.tab_1)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(55, 180, 420, 3))
        palette2 = QPalette()
        palette2.setBrush(QPalette.Active, QPalette.Button, brush2)
        palette2.setBrush(QPalette.Active, QPalette.Light, brush3)
        palette2.setBrush(QPalette.Active, QPalette.Base, brush2)
        palette2.setBrush(QPalette.Active, QPalette.Window, brush2)
        palette2.setBrush(QPalette.Inactive, QPalette.Button, brush2)
        palette2.setBrush(QPalette.Inactive, QPalette.Light, brush3)
        palette2.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        palette2.setBrush(QPalette.Inactive, QPalette.Window, brush2)
        palette2.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette2.setBrush(QPalette.Disabled, QPalette.Light, brush3)
        palette2.setBrush(QPalette.Disabled, QPalette.Base, brush2)
        palette2.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        self.line_3.setPalette(palette2)
        self.line_3.setStyleSheet(u"background-color: rgb(175, 175, 175);")
        self.line_3.setFrameShape(QFrame.HLine)
        self.line_3.setFrameShadow(QFrame.Sunken)
        self.line_4 = QFrame(self.tab_1)
        self.line_4.setObjectName(u"line_4")
        self.line_4.setGeometry(QRect(55, 140, 420, 3))
        palette3 = QPalette()
        palette3.setBrush(QPalette.Active, QPalette.Button, brush2)
        palette3.setBrush(QPalette.Active, QPalette.Light, brush3)
        palette3.setBrush(QPalette.Active, QPalette.Base, brush2)
        palette3.setBrush(QPalette.Active, QPalette.Window, brush2)
        palette3.setBrush(QPalette.Inactive, QPalette.Button, brush2)
        palette3.setBrush(QPalette.Inactive, QPalette.Light, brush3)
        palette3.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        palette3.setBrush(QPalette.Inactive, QPalette.Window, brush2)
        palette3.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette3.setBrush(QPalette.Disabled, QPalette.Light, brush3)
        palette3.setBrush(QPalette.Disabled, QPalette.Base, brush2)
        palette3.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        self.line_4.setPalette(palette3)
        self.line_4.setStyleSheet(u"background-color: rgb(175, 175, 175);")
        self.line_4.setFrameShape(QFrame.HLine)
        self.line_4.setFrameShadow(QFrame.Sunken)
        self.line_5 = QFrame(self.tab_1)
        self.line_5.setObjectName(u"line_5")
        self.line_5.setGeometry(QRect(55, 100, 420, 3))
        palette4 = QPalette()
        palette4.setBrush(QPalette.Active, QPalette.Button, brush2)
        palette4.setBrush(QPalette.Active, QPalette.Light, brush3)
        palette4.setBrush(QPalette.Active, QPalette.Base, brush2)
        palette4.setBrush(QPalette.Active, QPalette.Window, brush2)
        palette4.setBrush(QPalette.Inactive, QPalette.Button, brush2)
        palette4.setBrush(QPalette.Inactive, QPalette.Light, brush3)
        palette4.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        palette4.setBrush(QPalette.Inactive, QPalette.Window, brush2)
        palette4.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette4.setBrush(QPalette.Disabled, QPalette.Light, brush3)
        palette4.setBrush(QPalette.Disabled, QPalette.Base, brush2)
        palette4.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        self.line_5.setPalette(palette4)
        self.line_5.setStyleSheet(u"background-color: rgb(175, 175, 175);")
        self.line_5.setFrameShape(QFrame.HLine)
        self.line_5.setFrameShadow(QFrame.Sunken)
        self.line_6 = QFrame(self.tab_1)
        self.line_6.setObjectName(u"line_6")
        self.line_6.setGeometry(QRect(55, 220, 420, 3))
        palette5 = QPalette()
        palette5.setBrush(QPalette.Active, QPalette.Button, brush2)
        palette5.setBrush(QPalette.Active, QPalette.Light, brush3)
        palette5.setBrush(QPalette.Active, QPalette.Base, brush2)
        palette5.setBrush(QPalette.Active, QPalette.Window, brush2)
        palette5.setBrush(QPalette.Inactive, QPalette.Button, brush2)
        palette5.setBrush(QPalette.Inactive, QPalette.Light, brush3)
        palette5.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        palette5.setBrush(QPalette.Inactive, QPalette.Window, brush2)
        palette5.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette5.setBrush(QPalette.Disabled, QPalette.Light, brush3)
        palette5.setBrush(QPalette.Disabled, QPalette.Base, brush2)
        palette5.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        self.line_6.setPalette(palette5)
        self.line_6.setStyleSheet(u"background-color: rgb(175, 175, 175);")
        self.line_6.setFrameShape(QFrame.HLine)
        self.line_6.setFrameShadow(QFrame.Sunken)
        self.line_7 = QFrame(self.tab_1)
        self.line_7.setObjectName(u"line_7")
        self.line_7.setGeometry(QRect(55, 260, 420, 3))
        palette6 = QPalette()
        palette6.setBrush(QPalette.Active, QPalette.Button, brush2)
        palette6.setBrush(QPalette.Active, QPalette.Light, brush3)
        palette6.setBrush(QPalette.Active, QPalette.Base, brush2)
        palette6.setBrush(QPalette.Active, QPalette.Window, brush2)
        palette6.setBrush(QPalette.Inactive, QPalette.Button, brush2)
        palette6.setBrush(QPalette.Inactive, QPalette.Light, brush3)
        palette6.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        palette6.setBrush(QPalette.Inactive, QPalette.Window, brush2)
        palette6.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette6.setBrush(QPalette.Disabled, QPalette.Light, brush3)
        palette6.setBrush(QPalette.Disabled, QPalette.Base, brush2)
        palette6.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        self.line_7.setPalette(palette6)
        self.line_7.setStyleSheet(u"background-color: rgb(175, 175, 175);")
        self.line_7.setFrameShape(QFrame.HLine)
        self.line_7.setFrameShadow(QFrame.Sunken)
        self.line_8 = QFrame(self.tab_1)
        self.line_8.setObjectName(u"line_8")
        self.line_8.setGeometry(QRect(55, 340, 420, 3))
        palette7 = QPalette()
        palette7.setBrush(QPalette.Active, QPalette.Button, brush2)
        palette7.setBrush(QPalette.Active, QPalette.Light, brush3)
        palette7.setBrush(QPalette.Active, QPalette.Base, brush2)
        palette7.setBrush(QPalette.Active, QPalette.Window, brush2)
        palette7.setBrush(QPalette.Inactive, QPalette.Button, brush2)
        palette7.setBrush(QPalette.Inactive, QPalette.Light, brush3)
        palette7.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        palette7.setBrush(QPalette.Inactive, QPalette.Window, brush2)
        palette7.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette7.setBrush(QPalette.Disabled, QPalette.Light, brush3)
        palette7.setBrush(QPalette.Disabled, QPalette.Base, brush2)
        palette7.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        self.line_8.setPalette(palette7)
        self.line_8.setStyleSheet(u"background-color: rgb(175, 175, 175);")
        self.line_8.setFrameShape(QFrame.HLine)
        self.line_8.setFrameShadow(QFrame.Sunken)
        self.line_9 = QFrame(self.tab_1)
        self.line_9.setObjectName(u"line_9")
        self.line_9.setGeometry(QRect(55, 485, 420, 3))
        palette8 = QPalette()
        palette8.setBrush(QPalette.Active, QPalette.Button, brush2)
        palette8.setBrush(QPalette.Active, QPalette.Light, brush3)
        palette8.setBrush(QPalette.Active, QPalette.Base, brush2)
        palette8.setBrush(QPalette.Active, QPalette.Window, brush2)
        palette8.setBrush(QPalette.Inactive, QPalette.Button, brush2)
        palette8.setBrush(QPalette.Inactive, QPalette.Light, brush3)
        palette8.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        palette8.setBrush(QPalette.Inactive, QPalette.Window, brush2)
        palette8.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette8.setBrush(QPalette.Disabled, QPalette.Light, brush3)
        palette8.setBrush(QPalette.Disabled, QPalette.Base, brush2)
        palette8.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        self.line_9.setPalette(palette8)
        self.line_9.setStyleSheet(u"background-color: rgb(175, 175, 175);")
        self.line_9.setFrameShape(QFrame.HLine)
        self.line_9.setFrameShadow(QFrame.Sunken)
        self.line_10 = QFrame(self.tab_1)
        self.line_10.setObjectName(u"line_10")
        self.line_10.setGeometry(QRect(55, 525, 420, 3))
        palette9 = QPalette()
        palette9.setBrush(QPalette.Active, QPalette.Button, brush2)
        palette9.setBrush(QPalette.Active, QPalette.Light, brush3)
        palette9.setBrush(QPalette.Active, QPalette.Base, brush2)
        palette9.setBrush(QPalette.Active, QPalette.Window, brush2)
        palette9.setBrush(QPalette.Inactive, QPalette.Button, brush2)
        palette9.setBrush(QPalette.Inactive, QPalette.Light, brush3)
        palette9.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        palette9.setBrush(QPalette.Inactive, QPalette.Window, brush2)
        palette9.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette9.setBrush(QPalette.Disabled, QPalette.Light, brush3)
        palette9.setBrush(QPalette.Disabled, QPalette.Base, brush2)
        palette9.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        self.line_10.setPalette(palette9)
        self.line_10.setStyleSheet(u"background-color: rgb(175, 175, 175);")
        self.line_10.setFrameShape(QFrame.HLine)
        self.line_10.setFrameShadow(QFrame.Sunken)
        self.line_11 = QFrame(self.tab_1)
        self.line_11.setObjectName(u"line_11")
        self.line_11.setGeometry(QRect(55, 565, 420, 3))
        palette10 = QPalette()
        palette10.setBrush(QPalette.Active, QPalette.Button, brush2)
        palette10.setBrush(QPalette.Active, QPalette.Light, brush3)
        palette10.setBrush(QPalette.Active, QPalette.Base, brush2)
        palette10.setBrush(QPalette.Active, QPalette.Window, brush2)
        palette10.setBrush(QPalette.Inactive, QPalette.Button, brush2)
        palette10.setBrush(QPalette.Inactive, QPalette.Light, brush3)
        palette10.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        palette10.setBrush(QPalette.Inactive, QPalette.Window, brush2)
        palette10.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette10.setBrush(QPalette.Disabled, QPalette.Light, brush3)
        palette10.setBrush(QPalette.Disabled, QPalette.Base, brush2)
        palette10.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        self.line_11.setPalette(palette10)
        self.line_11.setStyleSheet(u"background-color: rgb(175, 175, 175);")
        self.line_11.setFrameShape(QFrame.HLine)
        self.line_11.setFrameShadow(QFrame.Sunken)
        self.line_12 = QFrame(self.tab_1)
        self.line_12.setObjectName(u"line_12")
        self.line_12.setGeometry(QRect(55, 605, 420, 3))
        palette11 = QPalette()
        palette11.setBrush(QPalette.Active, QPalette.Button, brush2)
        palette11.setBrush(QPalette.Active, QPalette.Light, brush3)
        palette11.setBrush(QPalette.Active, QPalette.Base, brush2)
        palette11.setBrush(QPalette.Active, QPalette.Window, brush2)
        palette11.setBrush(QPalette.Inactive, QPalette.Button, brush2)
        palette11.setBrush(QPalette.Inactive, QPalette.Light, brush3)
        palette11.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        palette11.setBrush(QPalette.Inactive, QPalette.Window, brush2)
        palette11.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette11.setBrush(QPalette.Disabled, QPalette.Light, brush3)
        palette11.setBrush(QPalette.Disabled, QPalette.Base, brush2)
        palette11.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        self.line_12.setPalette(palette11)
        self.line_12.setStyleSheet(u"background-color: rgb(175, 175, 175);")
        self.line_12.setFrameShape(QFrame.HLine)
        self.line_12.setFrameShadow(QFrame.Sunken)
        self.line_13 = QFrame(self.tab_1)
        self.line_13.setObjectName(u"line_13")
        self.line_13.setGeometry(QRect(55, 645, 420, 3))
        palette12 = QPalette()
        palette12.setBrush(QPalette.Active, QPalette.Button, brush2)
        palette12.setBrush(QPalette.Active, QPalette.Light, brush3)
        palette12.setBrush(QPalette.Active, QPalette.Base, brush2)
        palette12.setBrush(QPalette.Active, QPalette.Window, brush2)
        palette12.setBrush(QPalette.Inactive, QPalette.Button, brush2)
        palette12.setBrush(QPalette.Inactive, QPalette.Light, brush3)
        palette12.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        palette12.setBrush(QPalette.Inactive, QPalette.Window, brush2)
        palette12.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette12.setBrush(QPalette.Disabled, QPalette.Light, brush3)
        palette12.setBrush(QPalette.Disabled, QPalette.Base, brush2)
        palette12.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        self.line_13.setPalette(palette12)
        self.line_13.setStyleSheet(u"background-color: rgb(175, 175, 175);")
        self.line_13.setFrameShape(QFrame.HLine)
        self.line_13.setFrameShadow(QFrame.Sunken)
        self.line_14 = QFrame(self.tab_1)
        self.line_14.setObjectName(u"line_14")
        self.line_14.setGeometry(QRect(55, 685, 420, 3))
        palette13 = QPalette()
        palette13.setBrush(QPalette.Active, QPalette.Button, brush2)
        palette13.setBrush(QPalette.Active, QPalette.Light, brush3)
        palette13.setBrush(QPalette.Active, QPalette.Base, brush2)
        palette13.setBrush(QPalette.Active, QPalette.Window, brush2)
        palette13.setBrush(QPalette.Inactive, QPalette.Button, brush2)
        palette13.setBrush(QPalette.Inactive, QPalette.Light, brush3)
        palette13.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        palette13.setBrush(QPalette.Inactive, QPalette.Window, brush2)
        palette13.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette13.setBrush(QPalette.Disabled, QPalette.Light, brush3)
        palette13.setBrush(QPalette.Disabled, QPalette.Base, brush2)
        palette13.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        self.line_14.setPalette(palette13)
        self.line_14.setStyleSheet(u"background-color: rgb(175, 175, 175);")
        self.line_14.setFrameShape(QFrame.HLine)
        self.line_14.setFrameShadow(QFrame.Sunken)
        self.line_15 = QFrame(self.tab_1)
        self.line_15.setObjectName(u"line_15")
        self.line_15.setGeometry(QRect(55, 725, 420, 3))
        palette14 = QPalette()
        palette14.setBrush(QPalette.Active, QPalette.Button, brush2)
        palette14.setBrush(QPalette.Active, QPalette.Light, brush3)
        palette14.setBrush(QPalette.Active, QPalette.Base, brush2)
        palette14.setBrush(QPalette.Active, QPalette.Window, brush2)
        palette14.setBrush(QPalette.Inactive, QPalette.Button, brush2)
        palette14.setBrush(QPalette.Inactive, QPalette.Light, brush3)
        palette14.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        palette14.setBrush(QPalette.Inactive, QPalette.Window, brush2)
        palette14.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette14.setBrush(QPalette.Disabled, QPalette.Light, brush3)
        palette14.setBrush(QPalette.Disabled, QPalette.Base, brush2)
        palette14.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        self.line_15.setPalette(palette14)
        self.line_15.setStyleSheet(u"background-color: rgb(175, 175, 175);")
        self.line_15.setFrameShape(QFrame.HLine)
        self.line_15.setFrameShadow(QFrame.Sunken)
        self.line_16 = QFrame(self.tab_1)
        self.line_16.setObjectName(u"line_16")
        self.line_16.setGeometry(QRect(0, 440, 475, 3))
        palette15 = QPalette()
        palette15.setBrush(QPalette.Active, QPalette.Button, brush2)
        palette15.setBrush(QPalette.Active, QPalette.Light, brush3)
        palette15.setBrush(QPalette.Active, QPalette.Base, brush2)
        palette15.setBrush(QPalette.Active, QPalette.Window, brush2)
        palette15.setBrush(QPalette.Inactive, QPalette.Button, brush2)
        palette15.setBrush(QPalette.Inactive, QPalette.Light, brush3)
        palette15.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        palette15.setBrush(QPalette.Inactive, QPalette.Window, brush2)
        palette15.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette15.setBrush(QPalette.Disabled, QPalette.Light, brush3)
        palette15.setBrush(QPalette.Disabled, QPalette.Base, brush2)
        palette15.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        self.line_16.setPalette(palette15)
        self.line_16.setStyleSheet(u"background-color: rgb(175, 175, 175);")
        self.line_16.setFrameShape(QFrame.HLine)
        self.line_16.setFrameShadow(QFrame.Sunken)
        self.line_17 = QFrame(self.tab_1)
        self.line_17.setObjectName(u"line_17")
        self.line_17.setGeometry(QRect(0, 60, 475, 3))
        palette16 = QPalette()
        palette16.setBrush(QPalette.Active, QPalette.Button, brush2)
        palette16.setBrush(QPalette.Active, QPalette.Light, brush3)
        palette16.setBrush(QPalette.Active, QPalette.Base, brush2)
        palette16.setBrush(QPalette.Active, QPalette.Window, brush2)
        palette16.setBrush(QPalette.Inactive, QPalette.Button, brush2)
        palette16.setBrush(QPalette.Inactive, QPalette.Light, brush3)
        palette16.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        palette16.setBrush(QPalette.Inactive, QPalette.Window, brush2)
        palette16.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette16.setBrush(QPalette.Disabled, QPalette.Light, brush3)
        palette16.setBrush(QPalette.Disabled, QPalette.Base, brush2)
        palette16.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        self.line_17.setPalette(palette16)
        self.line_17.setStyleSheet(u"background-color: rgb(175, 175, 175);")
        self.line_17.setFrameShape(QFrame.HLine)
        self.line_17.setFrameShadow(QFrame.Sunken)
        self.line_18 = QFrame(self.tab_1)
        self.line_18.setObjectName(u"line_18")
        self.line_18.setGeometry(QRect(475, 60, 3, 283))
        palette17 = QPalette()
        palette17.setBrush(QPalette.Active, QPalette.Button, brush2)
        palette17.setBrush(QPalette.Active, QPalette.Light, brush3)
        palette17.setBrush(QPalette.Active, QPalette.Base, brush2)
        palette17.setBrush(QPalette.Active, QPalette.Window, brush2)
        palette17.setBrush(QPalette.Inactive, QPalette.Button, brush2)
        palette17.setBrush(QPalette.Inactive, QPalette.Light, brush3)
        palette17.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        palette17.setBrush(QPalette.Inactive, QPalette.Window, brush2)
        palette17.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette17.setBrush(QPalette.Disabled, QPalette.Light, brush3)
        palette17.setBrush(QPalette.Disabled, QPalette.Base, brush2)
        palette17.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        self.line_18.setPalette(palette17)
        self.line_18.setStyleSheet(u"background-color: rgb(175, 175, 175);")
        self.line_18.setFrameShape(QFrame.VLine)
        self.line_18.setFrameShadow(QFrame.Sunken)
        self.line_19 = QFrame(self.tab_1)
        self.line_19.setObjectName(u"line_19")
        self.line_19.setGeometry(QRect(475, 440, 3, 288))
        palette18 = QPalette()
        palette18.setBrush(QPalette.Active, QPalette.Button, brush2)
        palette18.setBrush(QPalette.Active, QPalette.Light, brush3)
        palette18.setBrush(QPalette.Active, QPalette.Base, brush2)
        palette18.setBrush(QPalette.Active, QPalette.Window, brush2)
        palette18.setBrush(QPalette.Inactive, QPalette.Button, brush2)
        palette18.setBrush(QPalette.Inactive, QPalette.Light, brush3)
        palette18.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        palette18.setBrush(QPalette.Inactive, QPalette.Window, brush2)
        palette18.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette18.setBrush(QPalette.Disabled, QPalette.Light, brush3)
        palette18.setBrush(QPalette.Disabled, QPalette.Base, brush2)
        palette18.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        self.line_19.setPalette(palette18)
        self.line_19.setStyleSheet(u"background-color: rgb(175, 175, 175);")
        self.line_19.setFrameShape(QFrame.VLine)
        self.line_19.setFrameShadow(QFrame.Sunken)
        self.QTab1.addTab(self.tab_1, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.GPU_WIDGET_CONT = QWidget(self.tab_2)
        self.GPU_WIDGET_CONT.setObjectName(u"GPU_WIDGET_CONT")
        self.GPU_WIDGET_CONT.setGeometry(QRect(440, 400, 561, 301))
        self.pushButton_2 = QPushButton(self.GPU_WIDGET_CONT)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(180, 90, 75, 23))
        self.gpu_temp_check = QCheckBox(self.tab_2)
        self.gpu_temp_check.setObjectName(u"gpu_temp_check")
        self.gpu_temp_check.setGeometry(QRect(30, 680, 81, 21))
        self.gpu_temp_check.setChecked(True)
        self.gpu_temp_check.setTristate(False)
        self.gpu_fan_check = QCheckBox(self.tab_2)
        self.gpu_fan_check.setObjectName(u"gpu_fan_check")
        self.gpu_fan_check.setGeometry(QRect(262, 680, 151, 21))
        self.gpu_fan_check.setChecked(True)
        self.gpu_memory_check = QCheckBox(self.tab_2)
        self.gpu_memory_check.setObjectName(u"gpu_memory_check")
        self.gpu_memory_check.setGeometry(QRect(121, 680, 131, 21))
        self.gpu_memory_check.setChecked(True)
        self.cpu_temp_check = QCheckBox(self.tab_2)
        self.cpu_temp_check.setObjectName(u"cpu_temp_check")
        self.cpu_temp_check.setGeometry(QRect(30, 321, 101, 21))
        self.cpu_temp_check.setChecked(True)
        self.cpu_load_check = QCheckBox(self.tab_2)
        self.cpu_load_check.setObjectName(u"cpu_load_check")
        self.cpu_load_check.setGeometry(QRect(140, 321, 101, 21))
        self.cpu_load_check.setChecked(True)
        self.LABEL_GRAPHS_INFO = QLabel(self.tab_2)
        self.LABEL_GRAPHS_INFO.setObjectName(u"LABEL_GRAPHS_INFO")
        self.LABEL_GRAPHS_INFO.setGeometry(QRect(30, 30, 391, 161))
        self.LABEL_GRAPHS_INFO.setContextMenuPolicy(Qt.PreventContextMenu)
        self.label_time = QLabel(self.tab_2)
        self.label_time.setObjectName(u"label_time")
        self.label_time.setGeometry(QRect(30, 460, 221, 31))
        self.label_data_amount = QLabel(self.tab_2)
        self.label_data_amount.setObjectName(u"label_data_amount")
        self.label_data_amount.setGeometry(QRect(30, 491, 221, 31))
        self.LABEL_GPU = QLabel(self.tab_2)
        self.LABEL_GPU.setObjectName(u"LABEL_GPU")
        self.LABEL_GPU.setGeometry(QRect(30, 640, 321, 31))
        self.LABEL_CPU = QLabel(self.tab_2)
        self.LABEL_CPU.setObjectName(u"LABEL_CPU")
        self.LABEL_CPU.setGeometry(QRect(30, 281, 321, 31))
        self.verticalLayoutWidget = QWidget(self.tab_2)
        self.verticalLayoutWidget.setObjectName(u"verticalLayoutWidget")
        self.verticalLayoutWidget.setGeometry(QRect(540, 30, 461, 311))
        self.verticalLayout = QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.pushButton = QPushButton(self.verticalLayoutWidget)
        self.pushButton.setObjectName(u"pushButton")

        self.verticalLayout.addWidget(self.pushButton)

        self.QTab1.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        self.QTab1.setCurrentIndex(1)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Ukazatel teplot", None))
        self.CPU_MAIN_LABEL.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">CPU - procesor</span></p></body></html>", None))
        self.GPU_MAIN_LABEL.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">GPU - grafick\u00fd \u010dip</span></p></body></html>", None))
        self.cpu_frequency_label.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:12pt;\">Frekvence procesoru MHz: </span></p></body></html>", None))
        self.cpu_cores_label.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:12pt;\">Po\u010det jader: </span></p></body></html>", None))
        self.cpu_name_label.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:12pt;\">N\u00e1zev procesoru: AMD Athlon II X4 640 Processor</span></p></body></html>", None))
        self.cpu_min_temperature_label.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:12pt;\">Nejmen\u0161\u00ed nam\u011b\u0159en\u00e1 teplota \u00b0C: </span></p></body></html>", None))
        self.cpu_max_temperature_label.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:12pt;\">Nejv\u011bt\u0161\u00ed nam\u011b\u0159en\u00e1 teplota \u00b0C: </span></p></body></html>", None))
        self.cpu_load_label.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:12pt;\">Aktu\u00e1ln\u00ed z\u00e1t\u011b\u017e procesoru %: </span></p></body></html>", None))
        self.gpu_name_label.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:12pt;\">N\u00e1zev grafick\u00e9 karty: </span></p><p><span style=\" font-size:12pt;\"><br/></span></p></body></html>", None))
        self.gpu_total_memory_label.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:12pt;\">Celkov\u00e9 mno\u017estv\u00ed VRAM MB: </span></p></body></html>", None))
        self.gpu_memory_used_label.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:12pt;\">Aktu\u00e1ln\u00ed vyt\u00ed\u017een\u00ed pam\u011bti VRAM %: </span></p></body></html>", None))
        self.gpu_fan_load_label.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:12pt;\">Zat\u00ed\u017een\u00ed v\u011btr\u00e1\u010dk\u016f na grafick\u00e9 kart\u011b %: </span></p></body></html>", None))
        self.gpu_temperature_label.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:12pt;\">Aktu\u00e1ln\u00ed teplota C\u00b0: </span></p></body></html>", None))
        self.gpu_min_temperature_label.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:12pt;\">Nejmen\u0161\u00ed nam\u011b\u0159en\u00e1 teplota \u00b0C:</span></p></body></html>", None))
        self.cpu_actual_temperature_label.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:12pt;\">Aktu\u00e1ln\u00ed teplota \u00b0C: </span></p></body></html>", None))
        self.gpu_max_temp_label.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:12pt;\">Nejv\u011bt\u0161\u00ed nam\u011b\u0159en\u00e1 teplota \u00b0C:</span></p></body></html>", None))
        self.QTab1.setTabText(self.QTab1.indexOf(self.tab_1), QCoreApplication.translate("MainWindow", u"Sensory", None))
        self.pushButton_2.setText(QCoreApplication.translate("MainWindow", u"PushButton", None))
        self.gpu_temp_check.setText(QCoreApplication.translate("MainWindow", u"Teplota GPU", None))
        self.gpu_fan_check.setText(QCoreApplication.translate("MainWindow", u"Zat\u00ed\u017een\u00ed v\u011btr\u00e1\u010dku na GPU", None))
        self.gpu_memory_check.setText(QCoreApplication.translate("MainWindow", u"Vyt\u00ed\u017een\u00ed pam\u011bti VRAM", None))
        self.cpu_temp_check.setText(QCoreApplication.translate("MainWindow", u"Teplota CPU", None))
        self.cpu_load_check.setText(QCoreApplication.translate("MainWindow", u"Zat\u00ed\u017een\u00ed CPU", None))
        self.LABEL_GRAPHS_INFO.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Grafy zn\u00e1zor\u0148uj\u00edc\u00ed informace v z\u00e1vislosti na \u010dase.</span></p><p><span style=\" font-size:11pt; font-weight:600;\">Pro v\u00fdb\u011br sta\u010d\u00ed pomoc\u00ed zak\u0159\u00ed\u017ekov\u00e1n\u00ed vybrat dan\u00e9 </span></p><p><span style=\" font-size:11pt; font-weight:600;\">informace, kter\u00e9 se maj\u00ed na ose Y zobrazit. <br/><br/>Osa X je popsan\u00e1 \u010dasov\u011b, ka\u017ed\u00e1 aktualizace </span></p><p><span style=\" font-size:11pt; font-weight:600;\">prob\u00edh\u00e1 po 1s.</span></p></body></html>", None))
        self.label_time.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:12pt;\">D\u00e9lka m\u011b\u0159en\u00ed: </span></p></body></html>", None))
        self.label_data_amount.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:12pt;\">Po\u010det sekvenc\u00ed: </span></p></body></html>", None))
        self.LABEL_GPU.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Nastaven\u00ed osy Y pro GPU:</span></p></body></html>", None))
        self.LABEL_CPU.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Nastaven\u00ed osy Y pro CPU:</span></p></body></html>", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"PushButton", None))
        self.QTab1.setTabText(self.QTab1.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"Grafy", None))
    # retranslateUi

